trigger:
- main

pool:
  name: Default

steps:

- checkout: self

- script: |
    terraform version
  displayName: 'Terraform Version'

- script: |
    terraform init
  displayName: 'Terraform Init'

- script: |
    terraform validate
  displayName: 'Terraform Validate'

- script: |
    dir
    dir /s *.tf
  displayName: 'Check Terraform Files'

- script: |
    terraform plan
  displayName: 'Terraform Plan'
